import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bluetime - Competition</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading1='BLUETIME' heading2='' heading3='COMPETITION' message='We care about your car, and we deal to make your dreams come true'/>
    </div>
  )
}

